import type { EventsResponse, EventDetailResponse } from './types'

export const mockEventsResponse: EventsResponse = {
  success: true,
  total_events: 24,
  live_events: 8,
  available_sports: ['FÚTBOL', 'BASKET', 'TENIS', 'MOTOR', 'UFC'],
  events_by_sport: {
    'FÚTBOL': {
      total_events: 12,
      leagues_count: 4,
      leagues: {
        'La Liga': [
          {
            id: 1,
            title: 'Real Madrid vs Barcelona',
            league: 'La Liga',
            start_time: new Date().toISOString(),
            status: 'live',
            sport_category: 'FÚTBOL',
            home_team: 'Real Madrid',
            away_team: 'Barcelona',
            home_team_badge: 'https://media.api-sports.io/football/teams/541.png',
            away_team_badge: 'https://media.api-sports.io/football/teams/529.png',
            venue: 'Santiago Bernabéu',
            thumbnail_url: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800',
            has_stream: true,
          },
          {
            id: 2,
            title: 'Atlético Madrid vs Sevilla',
            league: 'La Liga',
            start_time: new Date(Date.now() + 3600000).toISOString(),
            status: 'scheduled',
            sport_category: 'FÚTBOL',
            home_team: 'Atlético Madrid',
            away_team: 'Sevilla',
            home_team_badge: 'https://media.api-sports.io/football/teams/530.png',
            away_team_badge: 'https://media.api-sports.io/football/teams/536.png',
            venue: 'Wanda Metropolitano',
            thumbnail_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
            has_stream: true,
          },
        ],
        'Premier League': [
          {
            id: 3,
            title: 'Manchester United vs Liverpool',
            league: 'Premier League',
            start_time: new Date().toISOString(),
            status: 'live',
            sport_category: 'FÚTBOL',
            home_team: 'Manchester United',
            away_team: 'Liverpool',
            home_team_badge: 'https://media.api-sports.io/football/teams/33.png',
            away_team_badge: 'https://media.api-sports.io/football/teams/40.png',
            venue: 'Old Trafford',
            thumbnail_url: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800',
            has_stream: true,
          },
          {
            id: 4,
            title: 'Chelsea vs Arsenal',
            league: 'Premier League',
            start_time: new Date(Date.now() + 7200000).toISOString(),
            status: 'scheduled',
            sport_category: 'FÚTBOL',
            home_team: 'Chelsea',
            away_team: 'Arsenal',
            home_team_badge: 'https://media.api-sports.io/football/teams/49.png',
            away_team_badge: 'https://media.api-sports.io/football/teams/42.png',
            venue: 'Stamford Bridge',
            thumbnail_url: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800',
            has_stream: true,
          },
          {
            id: 5,
            title: 'Manchester City vs Tottenham',
            league: 'Premier League',
            start_time: new Date(Date.now() + 10800000).toISOString(),
            status: 'scheduled',
            sport_category: 'FÚTBOL',
            home_team: 'Manchester City',
            away_team: 'Tottenham',
            home_team_badge: 'https://media.api-sports.io/football/teams/50.png',
            away_team_badge: 'https://media.api-sports.io/football/teams/47.png',
            venue: 'Etihad Stadium',
            thumbnail_url: 'https://images.unsplash.com/photo-1508098682722-e99c643e7f0b?w=800',
            has_stream: true,
          },
        ],
        'Champions League': [
          {
            id: 6,
            title: 'Bayern Munich vs PSG',
            league: 'Champions League',
            start_time: new Date().toISOString(),
            status: 'live',
            sport_category: 'FÚTBOL',
            home_team: 'Bayern Munich',
            away_team: 'PSG',
            home_team_badge: 'https://media.api-sports.io/football/teams/157.png',
            away_team_badge: 'https://media.api-sports.io/football/teams/85.png',
            venue: 'Allianz Arena',
            thumbnail_url: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800',
            has_stream: true,
          },
        ],
        'Serie A': [
          {
            id: 7,
            title: 'Juventus vs Inter Milan',
            league: 'Serie A',
            start_time: new Date(Date.now() + 5400000).toISOString(),
            status: 'scheduled',
            sport_category: 'FÚTBOL',
            home_team: 'Juventus',
            away_team: 'Inter Milan',
            home_team_badge: 'https://media.api-sports.io/football/teams/496.png',
            away_team_badge: 'https://media.api-sports.io/football/teams/505.png',
            venue: 'Allianz Stadium',
            thumbnail_url: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800',
            has_stream: true,
          },
        ],
      },
    },
    'BASKET': {
      total_events: 6,
      leagues_count: 2,
      leagues: {
        'NBA': [
          {
            id: 8,
            title: 'Lakers vs Warriors',
            league: 'NBA',
            start_time: new Date().toISOString(),
            status: 'live',
            sport_category: 'BASKET',
            home_team: 'Los Angeles Lakers',
            away_team: 'Golden State Warriors',
            home_team_badge: null,
            away_team_badge: null,
            venue: 'Crypto.com Arena',
            thumbnail_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
            has_stream: true,
          },
          {
            id: 9,
            title: 'Celtics vs Heat',
            league: 'NBA',
            start_time: new Date(Date.now() + 3600000).toISOString(),
            status: 'scheduled',
            sport_category: 'BASKET',
            home_team: 'Boston Celtics',
            away_team: 'Miami Heat',
            home_team_badge: null,
            away_team_badge: null,
            venue: 'TD Garden',
            thumbnail_url: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=800',
            has_stream: true,
          },
        ],
        'Euroliga': [
          {
            id: 10,
            title: 'Real Madrid vs Barcelona',
            league: 'Euroliga',
            start_time: new Date().toISOString(),
            status: 'live',
            sport_category: 'BASKET',
            home_team: 'Real Madrid',
            away_team: 'Barcelona',
            home_team_badge: null,
            away_team_badge: null,
            venue: 'WiZink Center',
            thumbnail_url: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800',
            has_stream: true,
          },
        ],
      },
    },
    'TENIS': {
      total_events: 4,
      leagues_count: 2,
      leagues: {
        'ATP Masters': [
          {
            id: 11,
            title: 'Alcaraz vs Djokovic',
            league: 'ATP Masters',
            start_time: new Date().toISOString(),
            status: 'live',
            sport_category: 'TENIS',
            home_team: 'Carlos Alcaraz',
            away_team: 'Novak Djokovic',
            home_team_badge: null,
            away_team_badge: null,
            venue: 'Indian Wells',
            thumbnail_url: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800',
            has_stream: true,
          },
        ],
        'WTA': [
          {
            id: 12,
            title: 'Swiatek vs Sabalenka',
            league: 'WTA',
            start_time: new Date(Date.now() + 7200000).toISOString(),
            status: 'scheduled',
            sport_category: 'TENIS',
            home_team: 'Iga Swiatek',
            away_team: 'Aryna Sabalenka',
            home_team_badge: null,
            away_team_badge: null,
            venue: 'Miami Open',
            thumbnail_url: 'https://images.unsplash.com/photo-1587280501635-68a0e82cd5ff?w=800',
            has_stream: true,
          },
        ],
      },
    },
    'MOTOR': {
      total_events: 2,
      leagues_count: 2,
      leagues: {
        'Formula 1': [
          {
            id: 13,
            title: 'GP Bahrain - Carrera',
            league: 'Formula 1',
            start_time: new Date(Date.now() + 14400000).toISOString(),
            status: 'scheduled',
            sport_category: 'MOTOR',
            home_team: null,
            away_team: null,
            home_team_badge: null,
            away_team_badge: null,
            venue: 'Circuito de Bahrain',
            thumbnail_url: 'https://images.unsplash.com/photo-1541746972996-4e0b0f43e02a?w=800',
            has_stream: true,
          },
        ],
        'MotoGP': [
          {
            id: 14,
            title: 'GP Qatar - MotoGP',
            league: 'MotoGP',
            start_time: new Date().toISOString(),
            status: 'live',
            sport_category: 'MOTOR',
            home_team: null,
            away_team: null,
            home_team_badge: null,
            away_team_badge: null,
            venue: 'Circuito de Losail',
            thumbnail_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
            has_stream: true,
          },
        ],
      },
    },
    'UFC': {
      total_events: 2,
      leagues_count: 1,
      leagues: {
        'UFC': [
          {
            id: 15,
            title: 'UFC 300 - Pereira vs Prochazka',
            league: 'UFC',
            start_time: new Date(Date.now() + 18000000).toISOString(),
            status: 'scheduled',
            sport_category: 'UFC',
            home_team: 'Alex Pereira',
            away_team: 'Jiri Prochazka',
            home_team_badge: null,
            away_team_badge: null,
            venue: 'T-Mobile Arena',
            thumbnail_url: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800',
            has_stream: true,
          },
        ],
      },
    },
  },
}

export const mockEventDetail: EventDetailResponse = {
  success: true,
  event: {
    id: 1,
    title: 'Real Madrid vs Barcelona',
    league: 'La Liga',
    sport_category: 'FÚTBOL',
    start_time: new Date().toISOString(),
    status: 'live',
    home_team: 'Real Madrid',
    away_team: 'Barcelona',
    home_team_badge: 'https://media.api-sports.io/football/teams/541.png',
    away_team_badge: 'https://media.api-sports.io/football/teams/529.png',
    venue: 'Santiago Bernabéu',
    thumbnail_url: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800',
  },
  own_stream: {
    name: 'ZICOTV HD',
    type: 'hls',
    output_path: '/streams/event-1/index.m3u8',
    is_streaming: true,
  },
  fallback_sources: [
    {
      id: 'src1',
      source: 'streamed',
      streams: [
        { embedUrl: 'https://example.com/embed/1', hd: true, language: 'es', viewers: 1250 },
        { embedUrl: 'https://example.com/embed/2', hd: false, language: 'en', viewers: 890 },
      ],
    },
  ],
}
